# The Cobb-Douglas function

P(L, K) = b* L^a * K^(1-a)

P: total production

L: labor input

K: capital input

b: total factor productivity

a: the output elasticties of labor


Question: Find a and b

| Year | P | L | K |
|------|------|------|------|
|1899|100|100|100|
|1900|101|105|107|
|1901|112|110|114|
|1902|122|117|122|
|1903|124|122|131|
|1904|122|121|138|
|1905|143|125|149|
|1906|152|134|163|
|1907|151|140|176|
|1908|126|123|185|
|1909|155|143|198|
|1910|159|147|208|
|1911|153|148|216|
|1912|177|155|226|
|1913|184|156|236|
|1914|169|152|244|
|1915|189|156|266|
|1916|225|183|298|
|1917|227|198|335|
|1918|223|201|366|
|1919|218|196|387|
|1920|231|194|407|
|1921|179|146|417|
|1922|240|161|431|


log(P) = log(b) + a*log(L) + (1 - a)*log(K) = log(b) + (log(L) - log(K))*a + log(K)

=> log(P) - log(K) = [1, log(L) - log(K)] * [log(b), a].T

Y = log(P) - log(K)

X = [1, log(L) - log(K)].T

theta = [log(b), a].T

In [19]:
 # utils function
def plot_polynomial(xmin, xmax, coef, color='C1'):
    #xs is an array of evenly spaced numbers between xmin and xmax
    xs = np.linspace(xmin, xmax, num=500)
    
    #ys is an array, each element is computed as a polynomial function of
    #the corresponding element of xs
    ys = np.zeros_like(xs)
    for p, c in enumerate(coef.flatten()):
        ys += c*np.power(xs, p)
    plt.plot(xs, ys, color=color)

In [20]:
# Import data
import numpy as np

P = np.array([[100], [101], [112], [122], [124], [122], [143], [152], [151], [126], [155], [159], [153], [177], [184], [169], [189], [225], [227], [223], [218], [231], [179], [240]])
L = np.array([[100], [105], [110], [117], [122], [121], [125], [134], [140], [123], [143], [147], [148], [155], [156], [152], [156], [183], [198], [201], [196], [194], [146], [161]])
K = np.array([[100], [107], [114], [122], [131], [138], [149], [163], [176], [185], [198], [208], [216], [226], [236], [244], [266], [298], [335], [366], [387], [407], [417], [431]])


In [22]:
Y = np.log(P) - np.log(K)
X = np.concatenate((np.ones_like(L), np.log(L) - np.log(K)), axis=1)

In [23]:
X

array([[ 1.        ,  0.        ],
       [ 1.        , -0.01886848],
       [ 1.        , -0.03571808],
       [ 1.        , -0.04184711],
       [ 1.        , -0.07117628],
       [ 1.        , -0.13146314],
       [ 1.        , -0.17563257],
       [ 1.        , -0.1959104 ],
       [ 1.        , -0.22884157],
       [ 1.        , -0.40817147],
       [ 1.        , -0.3254224 ],
       [ 1.        , -0.34710549],
       [ 1.        , -0.37806613],
       [ 1.        , -0.37710988],
       [ 1.        , -0.4139758 ],
       [ 1.        , -0.4732877 ],
       [ 1.        , -0.5336403 ],
       [ 1.        , -0.48760733],
       [ 1.        , -0.5258635 ],
       [ 1.        , -0.59932843],
       [ 1.        , -0.68031003],
       [ 1.        , -0.74095503],
       [ 1.        , -1.0494796 ],
       [ 1.        , -0.98470373]])

In [24]:
Y

array([[ 0.        ],
       [-0.05770832],
       [-0.01769958],
       [ 0.        ],
       [-0.05491576],
       [-0.12323264],
       [-0.04110168],
       [-0.06986968],
       [-0.15320416],
       [-0.38407392],
       [-0.24484191],
       [-0.26863388],
       [-0.34484049],
       [-0.24438527],
       [-0.24889605],
       [-0.36726951],
       [-0.34174929],
       [-0.28099308],
       [-0.38918051],
       [-0.49546156],
       [-0.57392963],
       [-0.56639547],
       [-0.84570042],
       [-0.58546917]])

## Normal equation

In [47]:
theta = np.linalg.inv(X.T.dot(X)).dot(X.T.dot(Y))
theta

array([[0.00704403],
       [0.74460624]])

In [48]:
a = theta[1]
a


array([0.74460624])

In [49]:
b = np.exp(theta[0])
b

array([1.0070689])

In [28]:
TMP = b * (L**a) * (K**(1-a))
TMP

array([[100.70688978],
       [106.25302453],
       [111.79273444],
       [119.09308995],
       [125.11621838],
       [126.01607036],
       [131.65873444],
       [141.87099008],
       [149.4753001 ],
       [137.47922736],
       [156.49115814],
       [161.76185033],
       [164.15515299],
       [171.87726696],
       [174.62256494],
       [172.74202169],
       [180.04169096],
       [208.73427955],
       [228.0610412 ],
       [235.90134271],
       [234.84028079],
       [236.07215017],
       [192.22781265],
       [208.49927873]])

## Gradient descent

In [34]:
m = X.shape[0]
m

24

In [65]:
alpha = 0.1

In [87]:
def gradient_loss(X, Y, theta, m):
    return 1/m * X.T.dot(X.dot(theta) - Y)

def loss(X, Y, theta, m):
    return 1/(2*m) * np.sum((X.dot(theta) - Y)**2)

In [88]:
np.random.seed = 0.123
theta_2 = np.random.normal(size=2).reshape([2, 1])
theta_2

array([[-0.00955277],
       [-2.78409576]])

In [89]:
i = 0
for i in range(100000):
    grad = gradient_loss(X, Y, theta_2, m)
    theta_2 = theta_2 - alpha * grad
    if np.linalg.norm(grad)/m < 1e-10:
        break

In [90]:
theta_2

array([[0.00704402],
       [0.74460621]])

In [91]:
i

2655

In [92]:
loss(X, Y, theta_2, m)

0.0015646996868779886

In [93]:
a_2 = theta_2[1]
a_2

array([0.74460621])

In [94]:
b_2 = np.exp(theta_2[0])
b_2

array([1.00706888])